
export const ADMIN__RENDER_SECTION = 'ADMIN/RENDER_SECTION';
export const ADMIN__MODAL_WINDOW = 'ADMIN__MODAL_WINDOW';
// --------------------------------------------------------
export const AUTHORIZATION = 'ADMIN/AUTHORIZATION';



//--------------------------------- Create Product
export const ADD_PRODUCT__PRODUCT_CREATE = 'ADD_PRODUCT__PRODUCT_CREATE'
export const ADD_PRODUCT__CONFIRM_FORM = 'ADD_PRODUCT__CONFIRM_FORM'

// ----------------------------List Products--------------------------------------
export const LIST_PRODUCTS__GET_LIST = 'LIST_PRODUCTS__GET_LIST';
export const LIST_PRODUCTS__RENDER_MODAL_ALERT = 'LIST_PRODUCTS__RENDER_MODAL_ALERT';
export const LIST_PRODUCTS__DEL_PRODUCT = 'LIST_PRODUCTS__DEL_PRODUCT';
export const LIST_PRODUCTS__CHANGE_ACTIVITY = 'LIST_PRODUCTS__CHANGE_ACTIVITY';
// 
export const LIST_PRODUCTS__SET_NAME_FILTER = 'LIST_PRODUCTS__SET_NAME_FILTER';
export const LIST_PRODUCTS__FIND_PRODUCT = 'LIST_PRODUCTS__FIND_PRODUCT';
// 
export const LIST_PRODUCTS__GET_PRODUCTS_IN_CATEGORY = 'LIST_PRODUCTS__GET_PRODUCTS_IN_CATEGORY';
export const LIST_PRODUCTS__SELECT_PRODUCT = 'LIST_PRODUCTS__SELECT_PRODUCT';
export const LIST_PRODUCTS__DEL_ITEM_IN_LIST = 'LIST_PRODUCTS__DEL_ITEM_IN_LIST';
export const LIST_PRODUCTS__CREATE_PRODUCT = 'LIST_PRODUCTS__CREATE_PRODUCT';
export const LIST_PRODUCTS__ADD_NEW_PRODUCT = 'LIST_PRODUCTS__ADD_NEW_PRODUCT';

export const LIST_PRODUCTS__UPDATE_PRODUCT_IN_LIST = 'LIST_PRODUCTS__UPDATE_PRODUCT_IN_LIST';

//----------------------------- Edit Product ----------------------------------------

export const EDIT_PRODUCT__LOAD_PRODUCT = 'EDIT_PRODUCT__LOAD_PRODUCT';
export const EDIT_PRODUCT__EDIT = 'EDIT_PRODUCT__EDIT';
export const EDIT_PRODUCT__ADD_PREVIEW_IMG = 'EDIT_PRODUCT__ADD_PREVIEW_IMG';
export const EDIT_PRODUCT__PRELOADER_IMG = 'EDIT_PRODUCT__PRELOADER_IMG';
// 
export const EDIT_PRODUCT__LOAD_CATEGORY = 'EDIT_PRODUCT__LOAD_CATEGORY';
// 
export const EDIT_PRODUCT__LOAD_LIST_CATEGORY = 'EDIT_PRODUCT__LOAD_LIST_CATEGORY';
export const EDIT_PRODUCT__TOGGLE_LIST_CATEGORY = 'EDIT_PRODUCT__TOGGLE_LIST_CATEGORY';
export const EDIT_PRODUCT__OPEN_ITEM_CATEGORY = 'EDIT_PRODUCT__OPEN_ITEM_CATEGORY';
export const EDIT_PRODUCT__SELECTED_ITEM_CATEGORY = 'EDIT_PRODUCT__SELECTED_ITEM_CATEGORY';
// 
export const EDIT_PRODUCT__ADD_NEW_IMG_GALERY_PREVIEW = 'EDIT_PRODUCT__ADD_NEW_IMG_GALERY_PREVIEW';
export const EDIT_PRODUCT__GALERY_DELETE_IMG = 'EDIT_PRODUCT__GALERY_DELETE_IMG';
export const EDIT_PRODUCT__ADD_DETAIL = 'EDIT_PRODUCT__ADD_DETAIL';
export const EDIT_PRODUCT__ADD_NEW_DETAIL = 'EDIT_PRODUCT__ADD_NEW_DETAIL';
export const EDIT_PRODUCT__EDIT_DETAIL = 'EDIT_PRODUCT__EDIT_DETAIL';
export const EDIT_PRODUCT__DELETE_DETAIL = 'EDIT_PRODUCT__DELETE_DETAIL';
export const EDIT_PRODUCT__ADD_NEW_PROMO = 'EDIT_PRODUCT__ADD_NEW_PROMO';
export const EDIT_PRODUCT__PROMO_SET_DISCOUNT = 'EDIT_PRODUCT__PROMO_SET_DISCOUNT';
export const EDIT_PRODUCT__LOAD_LIST_PROMO = 'EDIT_PRODUCT__LOAD_LIST_PROMO';
export const EDIT_PRODUCT__DEL_ITEM_PROMO = 'EDIT_PRODUCT__DEL_ITEM_PROMO';
export const EDIT_PRODUCT__CANCEL_EDIT = 'EDIT_PRODUCT__CANCEL_EDIT';
export const EDIT_PRODUCT__UPDATE_PRODUCT = 'EDIT_PRODUCT__UPDATE_PRODUCT';

// -------------------------------- catalog

export const CATALOG__SET_NAME_DIR = 'CATALOG__SET_NAME_DIR';
export const CATALOG__CREATE_ITEM = 'CATALOG__CREATE_ITEM';
export const CATALOG__GET_LIST_ITEM = 'CATALOG__GET_LIST_ITEM';
export const CATALOG__EVENT_ADD_ITEM = 'CATALOG__EVENT_ADD_ITEM';
export const CATALOG__REMOVE_ADD_ITEM = 'REMOVE__EVENT_ADD_ITEM';
export const CATALOG__SUB_DIR = 'CATALOG__SUB_DIR';
export const CATALOG__CREATE_SUB_DIR = 'CATALOG__CREATE_SUB_DIR';
export const CATALOG__GET_SUB_ITEM = 'CATALOG__GET_SUB_ITEM';
export const CATALOG__SELECTED_ITEM = 'CATALOG__SELECTED_ITEM';

export const CATALOG__DEL_ITEM = 'CATALOG__DEL_ITEM';
export const CATALOG__EDIT_ITEM = 'CATALOG__EDIT_ITEM';
export const CATALOG__CANCEL_EDIT_ITEM = 'CATALOG__CANCEL_EDIT_ITEM';
export const CATALOG__NEW_NAME__EDIT_ITEM = 'CATALOG__NEW_NAME__EDIT_ITEM';
export const CATALOG__RENAME_EDIT_ITEM = 'CATALOG__RENAME_EDIT_ITEM';

export const CATALOG__CREATE_PRODUCT = 'CATALOG__CREATE_PRODUCT';
export const CATALOG__EDIT_PRODUCT = 'CATALOG__EDIT_PRODUCT';

// -------------------------------------choice

export const CHOICE__LOAD_LIST_CHOICE = 'CHOICE__LOAD_LIST_CHOICE';
