
export const ADMIN__RENDER_SECTION = 'ADMIN/RENDER_SECTION'
// --------------------------------------------------------
export const AUTHORIZATION = 'ADMIN/AUTHORIZATION';



//--------------------------------- Create Product
export const ADD_PRODUCT__PRODUCT_CREATE = 'ADD_PRODUCT__PRODUCT_CREATE'
export const ADD_PRODUCT__CONFIRM_FORM = 'ADD_PRODUCT__CONFIRM_FORM'

// ----------------------------List Products--------------------------------------
export const LIST_PRODUCTS__GET_LIST = 'LIST_PRODUCTS__GET_LIST';
export const LIST_PRODUCTS__RENDER_MODAL_ALERT = 'LIST_PRODUCTS__RENDER_MODAL_ALERT';
export const LIST_PRODUCTS__DEL_PRODUCT = 'LIST_PRODUCTS__DEL_PRODUCT';
export const LIST_PRODUCTS__CHANGE_ACTIVITY = 'LIST_PRODUCTS__CHANGE_ACTIVITY';

//----------------------------- Edit Product ----------------------------------------

export const EDIT_PRODUCT__LOAD_PRODUCT = 'EDIT_PRODUCT__LOAD_PRODUCT';
export const EDIT_PRODUCT__EDIT = 'EDIT_PRODUCT__EDIT';
export const EDIT_PRODUCT__ADD_PREVIEW_IMG = 'EDIT_PRODUCT__ADD_PREVIEW_IMG';
export const EDIT_PRODUCT__PRELOADER_IMG = 'EDIT_PRODUCT__PRELOADER_IMG';
export const EDIT_PRODUCT__LOAD_CATEGORY = 'EDIT_PRODUCT__LOAD_CATEGORY';
export const EDIT_PRODUCT__FLAG_CATEGORY = 'EDIT_PRODUCT__FLAG_CATEGORY';
export const EDIT_PRODUCT__CATEGORY_DROP = 'EDIT_PRODUCT__CATEGORY_DROP';
export const EDIT_PRODUCT__ADD_NAME_NEW_CATEGORY = 'EDIT_PRODUCT__ADD_NAME_NEW_CATEGORY';
export const EDIT_PRODUCT__ADD_NEW_CATEGORY = 'EDIT_PRODUCT__ADD_NEW_CATEGORY';
export const EDIT_PRODUCT__ADD_NEW_IMG_GALERY_PREVIEW = 'EDIT_PRODUCT__ADD_NEW_IMG_GALERY_PREVIEW';
export const EDIT_PRODUCT__GALERY_DELETE_IMG = 'EDIT_PRODUCT__GALERY_DELETE_IMG';
export const EDIT_PRODUCT__ADD_DETAIL = 'EDIT_PRODUCT__ADD_DETAIL';
export const EDIT_PRODUCT__ADD_NEW_DETAIL = 'EDIT_PRODUCT__ADD_NEW_DETAIL';
export const EDIT_PRODUCT__EDIT_DETAIL = 'EDIT_PRODUCT__EDIT_DETAIL';
export const EDIT_PRODUCT__DELETE_DETAIL = 'EDIT_PRODUCT__DELETE_DETAIL';
export const EDIT_PRODUCT__ADD_NEW_PROMO = 'EDIT_PRODUCT__ADD_NEW_PROMO';
export const EDIT_PRODUCT__PROMO_SET_DISCOUNT = 'EDIT_PRODUCT__PROMO_SET_DISCOUNT';
export const EDIT_PRODUCT__LOAD_LIST_PROMO = 'EDIT_PRODUCT__LOAD_LIST_PROMO';
export const EDIT_PRODUCT__SELECT_PROMO = 'EDIT_PRODUCT__SELECT_PROMO';
export const EDIT_PRODUCT__DEL_ITEM_PROMO = 'EDIT_PRODUCT__DEL_ITEM_PROMO';
export const EDIT_PRODUCT__CANCEL_EDIT = 'EDIT_PRODUCT__CANCEL_EDIT';
export const EDIT_PRODUCT__UPDATE_PRODUCT = 'EDIT_PRODUCT__UPDATE_PRODUCT';

