
export const ADMIN__RENDER_SECTION = 'ADMIN/RENDER_SECTION'
// --------------------------------------------------------
export const RENDER_FORM = 'PRODUCT/RENDER_FORM';
export const PRODUCT_CREATED = 'PRODUCT/PRODUCT_CREATED';
export const SET_NAME_PRODUCT = 'PRODUCT/SET_NAME_PRODUCT';
export const PRODUCT_CREATE_ALERT = 'PRODUCT/PRODUCT_CREATE_ALERT';
export const SET_PRODUCT_CATEGORY = 'PRODUCT/SET_CATEGORY';
export const AUTHORIZATION = 'ADMIN/AUTHORIZATION';
export const RENDER_FORM__CREATE_CATEGORY = 'CATEGORY/RENDER_FORM';
export const FORM_CATEGORY__SET_NAME_CATEGORY = 'CATEGORY/SET_NAME_CATEGORY';
export const FORM_PRODUCT__SET_PREVIEW_URL = 'PRODUCT/SET_PREVIEW_URL';


// -------------------------pageAdmin_addProduct-------------------
export const ADD_PRODUCT__SHOW_PANEL = 'ADMIN/ADD_PRODUCT/SHOW_PANEL';
export const ADD_PRODUCT__SET_TEMPLATE_DATA = 'ADMIN/SET_TEMPLATE_DATA';
export const ADD_PRODUCT__SET_FORM_NAME = 'ADMIN/SET_FORM_NAME';
export const ADD_PRODUCT__SET_FORM_BRAND = 'ADMIN/SET_FORM_BRAND';
export const ADD_PRODUCT__SET_FORM_PREVIEW = 'ADMIN/SET_FORM_PREVIEW';
export const ADD_PRODUCT__SET_FORM_SHORTDESCRIPTION = 'ADMIN/SET_FORM_SHORTDESCRIPTION';
export const ADD_PRODUCT__SET_FORM_PRICE = 'ADMIN/SET_FORM_PRICE';
export const ADD_PRODUCT__SET_FORM_PREVIEWS = 'ADMIN/SET_FORM_PREVIEWS';
export const ADD_PRODUCT__SET_FORM_CATEGORY = 'ADMIN/SET_FORM_CATEGORY';
export const ADD_PRODUCT__SET_FORM_DESCRIPTION = 'ADMIN/SET_FORM_DESCRIPTION';
export const ADD_PRODUCT__SET_FORM_DETALS = 'ADMIN/SET_FORM_DETALS';
export const ADD_PRODUCT__SET_FORM_PROMOTIONS = 'ADMIN/SET_FORM_PROMOTIONS';
export const ADD_PRODUCT__CLEAR_STATE = 'ADD_PRODUCT__CLEAR_STATE'
export const ADD_PRODUCT__PRODUCT_CREATE = 'ADD_PRODUCT__PRODUCT_CREATE'
export const ADD_PRODUCT__INFO_CREATED_PRODUCT = 'ADD_PRODUCT__INFO_CREATED_PRODUCT'
